### ISSUE TITLE
改了一点源码，就是在删除字符的地方，不添加的话，光标停留在空格的前面并不会往前移动一位

### ISSUE THREAD

**Issue by Alvin3225** [nanchen2251/BankCardUtils#5]
if (!isMiddle || count > 1) {
                    //如果是删除
                    if(count==0){
                        //如果删除时，光标停留在空格的前面，光标则要往前移一位
                        if (isSpace(start - before + 1)) {
                            setSelection((start - before) > 0 ? start - before : 0);
                        } else {
                            setSelection((start - before + 1) > s.length() ? s.length() : (start - before + 1));
                        }
                    }
                    //如果是增加
                    else{
                        setSelection(s.length() <= maxLength ? s.length() : maxLength);
                    }

                }

**Comment by nanchen2251** [comment]
合适的话，请直接 pull requests 吧
